sudo: false
language: node_js
node_js:
  - '0.12'
  - '4'
  - 'stable'
matrix:
  allow_failures:
    - node_js: '4'
    - node_js: 'stable'

# install node-canvas dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libcairo2-dev
    - libgif-dev
    - libjpeg8-dev
    - libpango1.0-dev

before_script:
  - npm run build
