sudo: false
dist: xenial
services:
  - xvfb
language: node_js
node_js:
  - '10'
  - '11'
  - '12'
  - 'stable'

# install node-canvas dependencies
addons:
  apt:
    packages:
    - g++-4.8
    - libcairo2-dev
    - libgif-dev
    - libjpeg8-dev
    - libpango1.0-dev

before_script:
  - npm run build

  # Run Firefox with a virtual screen
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
  - npm run coverage
  # TODO: report somewhere
  # - codeclimate-test-reporter < coverage/lcov.info
